/*
 * AboutDlg.java
 *
 * Created on November 20, 2006, 10:08 PM
 *
 * @author Robert Harrison
 *
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.ui;

import java.awt.Frame;
import javax.swing.JDialog;

/**
 * Displays info about Dyna
 * @author Robert Harrison
 *
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */
public class AboutDlg extends JDialog
{
    
    /** Creates new form AboutDlg */
    public AboutDlg(Frame owner)
    {
        super(owner, "About Dyna", true);
        
        initComponents();
        
        setSize(400, 400);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_textCtrl = new javax.swing.JTextArea();

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClose(evt);
            }
        });

        m_textCtrl.setColumns(20);
        m_textCtrl.setRows(5);
        m_textCtrl.setText("Dyna 1.1.1\n- A Protege plug-in for dynamic knowledge modeling\n\nAuthor: Robert Harrison\n\nAcknowledgements:\nI would like to thank the following people for their contributions to \nthis project:\n    - Daniel Obst - XMLManager class\n    - Yuxiang Wu - Event handling is based on Wu's Event Service\n    - Christine Chan - Developer of Inferential Modeling Technique (IMT) \n                               and Supervisor\n\nWe are also grateful for the generous support of a Research Grant \nfrom Natural Sciences and Engineering Research Council (NSERC) \nof Canada.\n\nEnergy Informatics Laboratory\nFaculty of Engineering\nUniversity of Regina\nRegina, Saskatchewan, Canada\n\nCopyright 2007, Energy Informatics Laboratory,  \nFaculty of Engineering, University of Regina. All rights reserved.\n\n");
        jScrollPane1.setViewportView(m_textCtrl);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(176, 176, 176)
                        .add(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onClose(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onClose
    {//GEN-HEADEREND:event_onClose
        this.dispose();
    }//GEN-LAST:event_onClose
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea m_textCtrl;
    // End of variables declaration//GEN-END:variables
    
}
