/*
 * TaskPriorityDlg.java
 *
 * Created on August 24, 2006, 1:33 PM
 *
 * @author Robert Harrison
 *
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.ui;

import java.awt.Frame;
import java.util.Vector;
import javax.swing.JDialog;
import ca.uregina.engg.eil.dyna.model.Task;

/**
 * Enables user to select a task and give it a priority (for creating task priorities)
 * @author Robert Harrison
 *
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */
public class TaskPriorityDlg extends JDialog
{
    protected Vector<Task> m_taskList;
    protected Task m_selTask;
    protected int m_priority;
    
    /**
     * Creates new form TaskPriorityDlg
     */
    public TaskPriorityDlg(Frame owner, Vector<Task> taskList)
    {
        super(owner, "Add Task to Objective", true);
        
        m_taskList = taskList;
        
        initComponents();
        
       //this.setVisible(true);
        
       setSize(280, 125);
       
       // Fill the list ctrl with tasks.       
       for (int i = 0; i < taskList.size(); i++)
       {
           fillTaskListCtrl(taskList.get(i));
       }
       
       m_selTask = null;
       m_priority = 1;
    }
    
    private void fillTaskListCtrl(Task task)
    {
        m_taskListCtrl.addItem(task);
        
        Vector<Task> subList = task.getSubTaskList();
        for (int i = 0; i < subList.size(); i++)
        {
            fillTaskListCtrl(subList.get(i));
        }
    }
    
    public Task getSelectedTask()
    {
        return m_selTask;
    }
    
    public int getPriority()
    {
        return m_priority;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        m_taskLabel = new javax.swing.JLabel();
        m_taskListCtrl = new javax.swing.JComboBox();
        m_priorityLabel = new javax.swing.JLabel();
        m_priorityCtrl = new javax.swing.JTextField();
        m_cancelButton = new javax.swing.JButton();
        m_okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        m_taskLabel.setText("Task:");

        m_priorityLabel.setText("Priority:");

        m_priorityCtrl.setText("1");

        m_cancelButton.setText("Cancel");
        m_cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onCancel(evt);
            }
        });

        m_okButton.setText("OK");
        m_okButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onOK(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(m_priorityLabel)
                    .add(m_taskLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(m_taskListCtrl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(m_priorityCtrl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .add(m_okButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(m_cancelButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(m_taskLabel)
                    .add(m_taskListCtrl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(m_priorityLabel)
                    .add(m_priorityCtrl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(m_cancelButton)
                    .add(m_okButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onCancel(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onCancel
    {//GEN-HEADEREND:event_onCancel
        this.dispose();
    }//GEN-LAST:event_onCancel

    private void onOK(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onOK
    {//GEN-HEADEREND:event_onOK
       
        m_selTask = (Task) m_taskListCtrl.getSelectedItem();
        
        Integer p = new Integer(m_priorityCtrl.getText());        
        m_priority = p.intValue();
        
        this.dispose();
    }//GEN-LAST:event_onOK
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton m_cancelButton;
    private javax.swing.JButton m_okButton;
    private javax.swing.JTextField m_priorityCtrl;
    private javax.swing.JLabel m_priorityLabel;
    private javax.swing.JLabel m_taskLabel;
    private javax.swing.JComboBox m_taskListCtrl;
    // End of variables declaration//GEN-END:variables
    
}
