/* Generated By:JJTree: Do not edit this line. ComplexVarDeclaration.java */

package ca.uregina.engg.eil.dyna.interpreter;

public class ComplexVarDeclaration extends SimpleNode {
  public ComplexVarDeclaration(int id) {
    super(id);
  }

  public ComplexVarDeclaration(TBLParser p, int id) {
    super(p, id);
  }

}
