/* Generated By:JJTree: Do not edit this line. IntLiteral.java */

/**
 * AST Node for integer literal values
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class IntLiteral extends SimpleNode {
  
  int m_value;
    
  public IntLiteral(int id) {
    super(id);
  }

  public IntLiteral(TBLParser p, int id) {
    super(p, id);
  }

  public void interpret() throws ParseException
  {     
      Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();        
      Stack stack = Stack.getStack();
      
      stack.push(new Integer(m_value));
  }
  
}
