/* Generated By:JJTree: Do not edit this line. PowExpr.java */

/**
 * AST Node for pow (**) expression
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class PowExpr extends SimpleNode {
  public PowExpr(int id) {
    super(id);
  }

  public PowExpr(TBLParser p, int id) {
    super(p, id);
  }

  public void interpret() throws ParseException
  {
     jjtGetChild(0).interpret();
     jjtGetChild(1).interpret();

     Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();        
     Stack stack = Stack.getStack();
     
     if (stack.peek() instanceof Integer)
     {
         int rhs = ((Integer)stack.pop()).intValue();
         int lhs = ((Integer)stack.pop()).intValue();
         Integer value = new Integer((int) Math.pow(lhs, rhs));
         
         stack.push(value);              
     }
     else if (stack.peek() instanceof Float)
     {
         float rhs = ((Float)stack.pop()).floatValue();
         float lhs = ((Float)stack.pop()).floatValue();
         Float value = new Float((float) Math.pow(lhs, rhs));
         
         stack.push(value);         
     }
  }
  
}
