/* Generated By:JJTree: Do not edit this line. PrintStmt.java */

/**
 * AST Node for print statement
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class PrintStmt extends SimpleNode {
  
  public PrintStmt(int id) {
    super(id);
  }

  public PrintStmt(TBLParser p, int id) {
    super(p, id);
  }
  
  public void interpret() throws ParseException
  {
     jjtGetChild(0).interpret();
          
     Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();       
     Stack stack = Stack.getStack();     
     PrintStream out = interp.getOut();
     
     if (stack.peek() instanceof Integer)
     {
         out.println(((Integer)stack.peek()).intValue());
     }
     else if (stack.peek() instanceof Float)
     {
         out.println(((Float)stack.peek()).floatValue());
     }
     else if (stack.peek() instanceof Boolean)
     {
         out.println(((Boolean)stack.peek()).booleanValue());
     }
     else if (stack.peek() instanceof String)
     {
         out.println(stack.peek());
     }
          
  }

}
