/* Generated By:JJTree: Do not edit this line. ReturnStmt.java */

package ca.uregina.engg.eil.dyna.interpreter;

import java.util.Hashtable;

public class ReturnStmt extends SimpleNode {
  public ReturnStmt(int id) {
    super(id);
  }

  public ReturnStmt(TBLParser p, int id) {
    super(p, id);
  }
  
  public void interpret() throws ParseException
  {      
      Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();       
      Stack stack = Stack.getStack();  
      
      jjtGetChild(0).interpret();    
      
      // Get the type of the return, so we can set the task
      //Hashtable<String, Object> symbolTable = SymbolTableHelper.getSymbolTable();
    
  }

}
