/* Generated By:JJTree: Do not edit this line. Root.java */

/**
 * The root AST Node
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class Root extends SimpleNode {
  public Root(int id) {
    super(id);
  }

  public Root(TBLParser p, int id) {
    super(p, id);
  }

  public void interpret() throws ParseException
  {      
     Stack stack = Stack.getStack();
      
     int numChildren = jjtGetNumChildren();

     for (int i = 0; i < numChildren; i++)
     {
        jjtGetChild(i).interpret();
        
        //stack.clear();
     }
 
  }
  
}
