/* Generated By:JJTree: Do not edit this line. TaskStmt.java */

/**
 * AST Node for Task statement
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class TaskStmt extends SimpleNode {
  public TaskStmt(int id) {
    super(id);
  }

  public TaskStmt(TBLParser p, int id) {
    super(p, id);
  }
  
  public void interpret() throws ParseException
  {
      jjtGetChild(0).interpret();
      
      String name = "";
     
      if (jjtGetChild(0) instanceof Id)
      {
            name = ((Id)jjtGetChild(0)).m_name;
      }
      
      Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();
              
      //interp.createDependency(name);      
  }

}
