/* Generated By:JJTree: Do not edit this line. ./TBLParserTreeConstants.java */

package ca.uregina.engg.eil.dyna.interpreter;

public interface TBLParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTTASKDEF = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTVOID = 3;
  public int JJTSTDDATATYPE = 4;
  public int JJTCUSTOMDATATYPE = 5;
  public int JJTPRINTSTMT = 6;
  public int JJTASSIGN = 7;
  public int JJTNOTEXPR = 8;
  public int JJTOREXPR = 9;
  public int JJTANDEXPR = 10;
  public int JJTXOREXPR = 11;
  public int JJTEQEQUAL = 12;
  public int JJTNOTEQUAL = 13;
  public int JJTLT = 14;
  public int JJTGT = 15;
  public int JJTLTEQUAL = 16;
  public int JJTGTEQUAL = 17;
  public int JJTMINUSEXPR = 18;
  public int JJTPLUSEXPR = 19;
  public int JJTMULEXPR = 20;
  public int JJTDIVEXPR = 21;
  public int JJTMODEXPR = 22;
  public int JJTPOWEXPR = 23;
  public int JJTATTRIBUTEREF = 24;
  public int JJTINTLITERAL = 25;
  public int JJTFLOATLITERAL = 26;
  public int JJTTRUE = 27;
  public int JJTFALSE = 28;
  public int JJTSTRINGLITERAL = 29;
  public int JJTID = 30;
  public int JJTSUITE = 31;
  public int JJTWHILESTMT = 32;
  public int JJTIFSTMT = 33;
  public int JJTASSERTSTMT = 34;
  public int JJTSQRTSTMT = 35;
  public int JJTFUNCALL = 36;
  public int JJTRETURNSTMT = 37;


  public String[] jjtNodeName = {
    "Root",
    "TaskDef",
    "VarDeclaration",
    "void",
    "StdDataType",
    "CustomDataType",
    "PrintStmt",
    "Assign",
    "NotExpr",
    "OrExpr",
    "AndExpr",
    "XorExpr",
    "EqEqual",
    "NotEqual",
    "LT",
    "GT",
    "LTEqual",
    "GTEqual",
    "MinusExpr",
    "PlusExpr",
    "MulExpr",
    "DivExpr",
    "ModExpr",
    "PowExpr",
    "AttributeRef",
    "IntLiteral",
    "FloatLiteral",
    "True",
    "False",
    "StringLiteral",
    "Id",
    "Suite",
    "WhileStmt",
    "IfStmt",
    "AssertStmt",
    "SqrtStmt",
    "FunCall",
    "ReturnStmt",
  };
}
