/* Generated By:JJTree: Do not edit this line. TestDef.java */

package ca.uregina.engg.eil.dyna.interpreter;

public class TestDef extends SimpleNode {
  public TestDef(int id) {
    super(id);
  }

  public TestDef(TBLParser p, int id) {
    super(p, id);
  }

  public void interpret() throws ParseException
  {
      int numChildren = jjtGetNumChildren();

      for (int i = 0; i < numChildren; i++)
      {
            jjtGetChild(i).interpret();
      }
  }
  
}
