/* Generated By:JJTree: Do not edit this line. TypeModifier.java */

package ca.uregina.engg.eil.dyna.interpreter;

public class TypeModifier extends SimpleNode {
    
  public String m_type;
    
  public TypeModifier(int id) {
    super(id);
  }

  public TypeModifier(TBLParser p, int id) {
    super(p, id);
  }
  
  public void interpret() throws ParseException
  {
    
  }

}
