/* Generated By:JJTree: Do not edit this line. FloatLiteral.java */

/**
 * AST Node for floating point literal values
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class FloatLiteral extends SimpleNode {
  
    float m_value;
    
    public FloatLiteral(int id) {
    super(id);
  }

  public FloatLiteral(TBLParser p, int id) {
    super(p, id);
  }

  public void interpret() throws ParseException
  {
      Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();        
      Stack stack = Stack.getStack();
      
      stack.push(new Float(m_value));     
  }
  
}
