/* Generated By:JJTree: Do not edit this line. NotExpr.java */

/**
 * AST Node for "not" expression
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class NotExpr extends SimpleNode {
  public NotExpr(int id) {
    super(id);
  }

  public NotExpr(TBLParser p, int id) {
    super(p, id);
  }

  public void interpret() throws ParseException
  {
     jjtGetChild(0).interpret();
     
     Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();        
     Stack stack = Stack.getStack();
     
     Boolean value = new Boolean(!((Boolean)stack.pop()).booleanValue());   
     
     stack.push(value);                     
  }
  
}
