/* Generated By:JJTree: Do not edit this line. PlusExpr.java */

/**
 * AST Node for plus (+) expression
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class PlusExpr extends SimpleNode {
  public PlusExpr(int id) {
    super(id);
  }

  public PlusExpr(TBLParser p, int id) {
    super(p, id);
  }

  public void interpret() throws ParseException
  {
     jjtGetChild(0).interpret();
     jjtGetChild(1).interpret();

     Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();        
     Stack stack = Stack.getStack();
     
     if (stack.peek() instanceof Integer)
     {
         Integer value = new Integer(((Integer)stack.pop()).intValue() +
                                     ((Integer)stack.pop()).intValue());
                  
         stack.push(value);                
     }
     else if (stack.peek() instanceof Float)
     {
         Float value = new Float(((Float)stack.pop()).floatValue() +
                                 ((Float)stack.pop()).floatValue());
         
         stack.push(value);                  
     }
  }
  
}
