/* Generated By:JJTree: Do not edit this line. SimpleVarDeclaration.java */

package ca.uregina.engg.eil.dyna.interpreter;

public class SimpleVarDeclaration extends SimpleNode {
  public SimpleVarDeclaration(int id) {
    super(id);
  }

  public SimpleVarDeclaration(TBLParser p, int id) {
    super(p, id);
  }

}
