/* Generated By:JJTree: Do not edit this line. SqrtStmt.java */

package ca.uregina.engg.eil.dyna.interpreter;

import java.io.PrintStream;
import java.lang.Math;

public class SqrtStmt extends SimpleNode {
  public SqrtStmt(int id) {
    super(id);
  }

  public SqrtStmt(TBLParser p, int id) {
    super(p, id);
  }

  public void interpret() throws ParseException
  {
      //Hashtable<String, Object> symbolTable = SymbolTableHelper.getSymbolTable();
      
     jjtGetChild(0).interpret();
        
     Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();
     Stack stack = Stack.getStack();       
     PrintStream out = interp.getOut();
          
     if (stack.peek() instanceof Integer)
     {
        int iValue = ((Integer) stack.pop()).intValue();
        double dValue = (double) iValue;
        
        double dResult = Math.sqrt(dValue);
        float fResult = new Float((float) dResult);
        
        stack.push(fResult);
        
     }          
     else if (stack.peek() instanceof Float)
     {
         float fValue = ((Float) stack.pop()).floatValue();
         double dValue = (double) fValue;
         
         double dResult = Math.sqrt(dValue);         
         float fResult = new Float((float) dResult);
         
         stack.push(fResult);
     }
     else if (stack.peek() instanceof String)
     {
         stack.pop();
         out.println("Error: cannot perform sqrt on string!");
     }
     
     
     
  }
  
}
