/* Generated By:JJTree: Do not edit this line. StdDataType.java */

/**
 * AST Node for a standard data type (int, float, string)
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class StdDataType extends SimpleNode {
  int m_type;
  String m_name;
    
  public StdDataType(int id) {
    super(id);
  }

  public StdDataType(TBLParser p, int id) {
    super(p, id);
  }
  
  public void interpret() throws ParseException
  {
      
  }

}
