/* Generated By:JJTree: Do not edit this line. StringLiteral.java */

/**
 * AST Node for string literal value
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class StringLiteral extends SimpleNode {
  
  String m_value;
    
  public StringLiteral(int id) {
    super(id);
  }

  public StringLiteral(TBLParser p, int id) {
    super(p, id);
  }

  public void interpret() throws ParseException
  {      
      Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();        
      Stack stack = Stack.getStack();
      
      stack.push(new String(m_value));     
  }
  
}
