/* Generated By:JJTree&JavaCC: Do not edit this line. TBLParserConstants.java */
package ca.uregina.engg.eil.dyna.interpreter;

public interface TBLParserConstants {

  int EOF = 0;
  int POWER = 8;
  int MULT = 9;
  int DIV = 10;
  int MOD = 11;
  int PLUS = 12;
  int MINUS = 13;
  int EQUALS = 14;
  int EQEQUAL = 15;
  int NOTEQUAL = 16;
  int LT = 17;
  int GT = 18;
  int LTEQUAL = 19;
  int GTEQUAL = 20;
  int OR = 21;
  int AND = 22;
  int NOT = 23;
  int XOR = 24;
  int LPAR = 25;
  int RPAR = 26;
  int DOT = 27;
  int LCBRACE = 28;
  int RCBRACE = 29;
  int LBRACK = 30;
  int RBRACK = 31;
  int COMMA = 32;
  int PRINT = 33;
  int INT = 34;
  int FLOAT = 35;
  int BOOLEAN = 36;
  int STRING = 37;
  int CLASS = 38;
  int WHILE = 39;
  int IF = 40;
  int ELSE = 41;
  int ASSERT = 42;
  int RETURN = 43;
  int TASK = 44;
  int SQRT = 45;
  int TRUE = 46;
  int FALSE = 47;
  int INT_LITERAL = 48;
  int FLOAT_LITERAL = 49;
  int STRING_LITERAL = 50;
  int IDENTIFIER = 51;
  int LETTER = 52;
  int DIGITS = 53;

  int DEFAULT = 0;
  int WithinComment1 = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"#\"",
    "\"\\n\"",
    "<token of kind 7>",
    "\"**\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"xor\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"print\"",
    "\"int\"",
    "\"float\"",
    "\"boolean\"",
    "\"string\"",
    "\"class\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"assert\"",
    "\"return\"",
    "\"task\"",
    "\"sqrt\"",
    "\"true\"",
    "\"false\"",
    "<INT_LITERAL>",
    "<FLOAT_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGITS>",
  };

}
