/* Generated By:JJTree: Do not edit this line. True.java */

/**
 * AST Node for "true"
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class True extends SimpleNode {
  public True(int id) {
    super(id);
  }

  public True(TBLParser p, int id) {
    super(p, id);
  }

  public void interpret() throws ParseException
  {
      Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();        
      Stack stack = Stack.getStack();
      
      stack.push(new Boolean(true));         
  }
  
}

