/* Generated By:JJTree: Do not edit this line. WhileStmt.java */

/**
 * AST Node for "while" statement
 *
 * @author Robert Harrison
 * 
 * Energy Informatics Laboratory
 * Faculty of Engineering
 * University of Regina
 * http://www.uregina.ca/engg
 */

package ca.uregina.engg.eil.dyna.interpreter;

import edu.stanford.smi.protege.model.KnowledgeBase;
import java.io.PrintStream;

public class WhileStmt extends SimpleNode {
  public WhileStmt(int id) {
    super(id);
  }

  public WhileStmt(TBLParser p, int id) {
    super(p, id);
  }
  
  public void interpret() throws ParseException
  {
        Interpreter interp = InterpreterManager.getInterpreterManager().getInterpreter();       
        Stack stack = Stack.getStack();
      
        while (true) 
        {
            jjtGetChild(0).interpret();
            
            if (((Boolean)stack.pop()).booleanValue())                       
            {
                jjtGetChild(1).interpret();
            }
            else
            {
                break;
            }
        } 
  }

}
